name: MobArena
main: com.garbagemule.MobArena.MobArena
version: 0.87
commands:
  mobarena:
    description: Base command for MobArena
    usage: |
           /mobarena join - Join the arena.
           /mobarena leave - Leave the arena.
  marena:
    description: Base command for MobArena
    usage: |
           /marena join - Join the arena.
           /marena leave - Leave the arena.
  ma:
    description: Base command for MobArena
    usage: |
           /ma join - Join the arena.
           /ma leave - Leave the arena.